# Generated by Django 4.2.2 on 2023-06-27 13:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_booking_service_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.AutoField(db_column='bookingID', default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='patente',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 6, 27, 9, 32, 42, 141517), verbose_name='Date'),
        ),
    ]
