# Generated by Django 4.2.2 on 2023-06-28 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_alter_service_date_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 28, 2, 20, 48, 909484, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(default=12345678, max_length=12),
        ),
    ]
