# Generated by Django 4.2.2 on 2023-06-28 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_alter_service_date_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 2, 27, 17, 674556, tzinfo=datetime.timezone.utc)),
        ),
    ]
