# Generated by Django 4.2.2 on 2023-06-28 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_booking_date_alter_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 2, 34, 41, 880934, tzinfo=datetime.timezone.utc)),
        ),
    ]
