# Generated by Django 4.2.2 on 2023-06-28 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_booking_finished_alter_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='finished',
            field=models.CharField(choices=[('F', 'Finalizado'), ('E', 'En Espera'), ('O', 'Otro')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 3, 0, 32, 294062, tzinfo=datetime.timezone.utc)),
        ),
    ]
