# Generated by Django 4.2.2 on 2023-06-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(db_column='genderId', primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('active', models.IntegerField()),
                ('gender', models.ForeignKey(db_column='genderId', on_delete=django.db.models.deletion.CASCADE, to='users.gender')),
            ],
        ),
    ]
